[tool.poetry]
name = "statsdir"
version = "0.0.2"
description = "statsdir."
authors = ["ChenyangGao <wosiwujm@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/ChenyangGao/web-mount-packs/tree/main/python-module/statsdir"
repository = "https://github.com/ChenyangGao/web-mount-packs/tree/main/python-module/statsdir"
keywords = ["statsdir", "statistics"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.scripts]
python-statsdir = "statsdir.__main__:main"
statsdir = "statsdir.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
iterdir = "^0.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.packages]]
include = "statsdir"
